### ISSUE TITLE
AutoCloseable.use with null receiver causes cryptic exception

### ISSUE THREAD

**Issue by vbezhenar** [Kotlin/kotlinx.support#4]
Test code:

```
// Kotlin
fun main(args: Array<String>) {
  MyResourceFactory.get().use {
    throw Exception("1")
  }
}

class MyResource : AutoCloseable {
  override fun close() {
    println("close")
  }
}

// Java
public class MyResourceFactory {
    public static MyResource get() {
        return null;
    }
}
```

This code results in this exception:

```
Exception in thread "main" java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlinx.support.jdk7.AutoCloseableKt.closeSuppressed, parameter $receiver
    at kotlinx.support.jdk7.AutoCloseableKt.closeSuppressed(AutoCloseable.kt)
    at test.MainKt.main(main.kt:31)
```

and original exception is eaten.

If I use Closeable and `use` from a standard library, error message is much clearer:

```
Exception in thread "main" java.lang.Exception: 1
```

**Comment by ilya-g** [comment]
Actually, with the current declaration of `use` function, it shouldn't allow the execution to pass to the `block` lambda when the receiver is `null`, because the receiver type is constrained as `T : AutoCloseable`, which means `T` cannot hold `null`.

However due to a missing null check in generic functions [KT-8135](https://youtrack.jetbrains.com/issue/KT-8135) this can go so far, so the `null` sneaks to the block where resource is get closed.

Currently we have two options:
- either implement workaround for KT-8135 and make `use` more strict about its receiver type nullability checking;
- or make `use` aware of possible `null` value of the receiver and relax type constraint of `T` to  `AutoCloseable?`.

UPD: Actual issue is [KT-12899](https://youtrack.jetbrains.com/issue/KT-12899)

**Comment by ilya-g** [comment]
After some discussions we have decided to stick with the option 2 — relax type constraint to allow nulls.
This would require corresponding changes in the standard library, so I've opened [KT-12894](https://youtrack.jetbrains.com/issue/KT-12894) for this.
